# Generated by Django 5.2.10 on 2026-02-28 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_data', models.BinaryField()),
                ('nonce', models.BinaryField(blank=True, null=True)),
                ('patient_wrapped_key', models.BinaryField(blank=True, null=True)),
                ('patient_wrap_nonce', models.BinaryField(blank=True, null=True)),
                ('category', models.CharField(choices=[('personal', 'Personal Details'), ('prescription', 'Prescription'), ('lab', 'Lab Report'), ('scan', 'Scan'), ('general', 'General')], default='general', max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AccessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=255)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='RecordAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='RecordDoctorKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapped_aes_key', models.BinaryField()),
                ('kyber_ciphertext', models.BinaryField()),
                ('wrap_nonce', models.BinaryField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
            ],
            options={
                'unique_together': {('record', 'doctor')},
            },
        ),
    ]
